### ISSUE TITLE
EOF Error occurs when using tail method with `from` and `to` arguments.

### ISSUE THREAD

**Issue by doryokujin** [treasure-data/td-client-ruby#2]
When i use tail method with from and to arguments (format is msgpack), 

( for exapmle: @td.tail(pay, count=100, to=1327048920, from=1327048800)  #reach last record before reaching count limit. )

then, "EOFError (end of file reached)" occurs from

td-client-ruby/lib/td/client/api.rb line 191:   code, body, res = get("/v3/table/tail/#{e db}/#{e table}", params)

**Comment by takkanm** [comment]
this feature is removed
