### ISSUE TITLE
Job#finished? not updated if @status is set

### ISSUE THREAD

**Issue by nahi** [treasure-data/td-client-ruby#31]
https://github.com/treasure-data/td-client-ruby/blob/33e23abb402f923c1bc304ea9c011dc3ca9a7781/lib/td/client/model.rb#L520-L524

This should be like;
```ruby
    update_progress! unless FINISHED_STATUS.include?(@status)
    FINISHED_STATUS.include?(@status)
```

**Comment by takkanm** [comment]
@nahi
I think that `#{stasuts}?` methods's policy was return by current status.
So, I think don't need to change.

Could you tell me reason for this proposal?

**Comment by nahi** [comment]
Sorry, I changed the link. The method I was talking is 'def finished?' which checks if a job is finished or not. 'finished?' should return the latest status I think.

**Comment by nurse** [comment]
`finished?` is considered just a convenient method about FINISHED_STATUS.
Network access should be
